# Generated by Django 2.1.5 on 2019-02-03 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_auto_20190109_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imagen', verbose_name='imagen_publicacion'),
            preserve_default=False,
        ),
    ]
