# Generated by Django 2.1.5 on 2019-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_auto_20190203_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to='C:\\Users\\joanc\\Python Projects\\BlogApp/media/'),
        ),
    ]
