# Generated by Django 2.1.5 on 2019-02-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_auto_20190203_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
    ]
