# Generated by Django 2.1.5 on 2019-02-03 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0006_remove_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='C:\\Users\\joanc\\Python Projects\\BlogApp/media/'),
            preserve_default=False,
        ),
    ]
