# Generated by Django 2.1.5 on 2019-02-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0008_detalles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalles',
            new_name='Detalle',
        ),
    ]
