# Generated by Django 2.1.5 on 2019-02-03 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0009_auto_20190203_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
